import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:go_router/go_router.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:provider/provider.dart';

import '../constants/constant.dart';
import '../data/data.dart';
import '../provider/providers.dart';
import '../router/app_router.dart';
import '../utils/utils.dart';
import '../widgets/widgets.dart';
part 'home_page.dart';
part 'abcdario_page.dart';
part 'translate_page.dart';
part 'settings_page.dart';
part 'detail_letter_page.dart';
