import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:flutter_swiper_view/flutter_swiper_view.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:go_router/go_router.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:pdf/pdf.dart';
import 'dart:math' as math;
import 'package:provider/provider.dart';
import 'package:speech_to_text/speech_recognition_result.dart';

import 'package:speech_to_text/speech_to_text.dart';
import 'package:templat_project/constants/shared_preferences_constants.dart';
import 'package:templat_project/custom_icons/custom_icons.dart';
import 'package:templat_project/helpers/helpers.dart';
import 'package:templat_project/services/services.dart';

import '../constants/constant.dart';
import '../data/menu_items_data.dart';
import '../env/environment_variables.dart';
import '../provider/providers.dart';
import '../router/app_router.dart';
import '../utils/utils.dart';
import '../widgets/widgets.dart';
part 'home_page.dart';
part 'abecedario_page.dart';
part 'translate_page.dart';
part 'settings_page.dart';
part 'detail_letter_page.dart';
part 'print_pdf_page.dart';
part 'welcome_page.dart';
part 'splash_screen_page.dart';
part 'phrase_maker_page.dart';
