const IS_DARK_MODE_ENABLED_KEY = 'IS_DARK_MODE_ENABLED_KEY';
const CURRENT_COLOR_KEY = 'CURRENT_COLOR_KEY';
const IS_FIRST_TIME_KEY = 'IS_FIRST_TIME_KEY';
const COUNTER_AD_KEY = 'COUNTER_AD_KEY';
const FCM_TOKEN = 'FCM_TOKEN';
